export type IntakeItemType = "蘭花" | "植物" | "永生花" | "落地花籃" | "其他";
export type SubstitutionPolicy = "由花藝師調整" | "替換前詢問客戶" | "不可替換";
export type AdminOrderIntakeItemDraft = { id:string; amount:string; itemType:IntakeItemType; mustKeep:string; plantRequest:string; quantity:string; referenceFocus:string; specialRequirements:string; substitutionPolicy:SubstitutionPolicy };
export type GiftUnitDraft = { id:string; cardText:string; items:AdminOrderIntakeItemDraft[] };
export type RecipientDraft = { id:string; recipientName:string; recipientTitle:string; recipientOrganization:string; deliveryAddress:string; building:string; floor:string; gifts:GiftUnitDraft[] };
export type AdminOrderIntakeDraft = { customerName:string; deliveryDate:string; rawSourceText:string; recipients:RecipientDraft[] };
export type AdminOrderIntakePreview = { cardTasks:Array<{id:string; recipient:string; cardText:string; status:"待打卡"}>; workCards:Array<{id:string; itemLabel:string; deliveryLabel:string; requirements:string[]}> };

export const createEmptyAdminOrderIntakeItem=(id:string):AdminOrderIntakeItemDraft=>({id,amount:"",itemType:"植物",mustKeep:"",plantRequest:"",quantity:"1",referenceFocus:"",specialRequirements:"",substitutionPolicy:"替換前詢問客戶"});
export const createEmptyGiftUnit=(id:string):GiftUnitDraft=>({id,cardText:"",items:[createEmptyAdminOrderIntakeItem(`${id}-item-1`)]});
export const createEmptyRecipient=(id:string):RecipientDraft=>({id,recipientName:"",recipientTitle:"",recipientOrganization:"",deliveryAddress:"",building:"",floor:"",gifts:[createEmptyGiftUnit(`${id}-gift-1`)]});
export const createEmptyAdminOrderIntakeDraft=():AdminOrderIntakeDraft=>({customerName:"",deliveryDate:"",rawSourceText:"",recipients:[createEmptyRecipient("recipient-1")]});
const positive=(v:string)=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null};
const amount=(v:string)=>{const t=v.replace(/[，,]/g,"").trim();const n=Number(t);return t&&Number.isFinite(n)&&n>=0?n:null};
const join=(p:string[])=>p.map(x=>x.trim()).filter(Boolean).join("｜");
export function validateAdminOrderIntake(d:AdminOrderIntakeDraft){const w:string[]=[];if(!d.rawSourceText.trim())w.push("尚未保留 LINE 原始訊息");if(!d.deliveryDate.trim())w.push("缺少交付日期");d.recipients.forEach((r,ri)=>{const label=`收禮人 ${ri+1}`;if(!r.recipientName.trim())w.push(`${label}：缺少收禮人`);if(!r.recipientTitle.trim())w.push(`${label}：缺少職稱`);if(!r.deliveryAddress.trim())w.push(`${label}：缺少配送地址`);r.gifts.forEach((g,gi)=>{if(!g.cardText.trim())w.push(`${label}・送禮單元 ${gi+1}：缺少完整賀卡內容`);g.items.forEach((i,ii)=>{if(!i.plantRequest.trim())w.push(`${label}・作品 ${ii+1}：尚未說明作品需求`);if(positive(i.quantity)===null)w.push(`${label}・作品 ${ii+1}：數量必須是大於 0 的整數`);if(amount(i.amount)===null)w.push(`${label}・作品 ${ii+1}：價位必須是 0 或正數`)})})});return w}
export function createAdminOrderIntakePreview(d:AdminOrderIntakeDraft):AdminOrderIntakePreview|null { const cards:AdminOrderIntakePreview["cardTasks"]=[],works:AdminOrderIntakePreview["workCards"]=[];let n=0;for(const r of d.recipients){const recipient=join([r.recipientName,r.recipientTitle,r.recipientOrganization]);const deliveryLabel=join([r.recipientName,r.recipientTitle,r.recipientOrganization,r.deliveryAddress,r.building,r.floor]);for(const g of r.gifts){cards.push({id:g.id,recipient,cardText:g.cardText.trim(),status:"待打卡"});for(const i of g.items){const a=amount(i.amount),q=positive(i.quantity);if(a===null||q===null)return null;for(let x=0;x<q;x++){n++;works.push({id:`${i.id}-${x}`,itemLabel:`第 ${n} 盆｜${i.itemType}｜NT$${a.toLocaleString("zh-TW")}`,deliveryLabel,requirements:[`指定／期待：${i.plantRequest||"請人工確認"}`,`缺貨處理：${i.substitutionPolicy}`]})}}}}return {cardTasks:cards,workCards:works} }
